My homework6
Bondarchuk97Ilja/homeworks-bondarchuk-ilja pull request #6
Opened 2019-04-30 15:55 UTC by Bondarchuk97Ilja

Два файла, отдельно для каждого слайда.

2019-04-30 15:55 UTC, Bondarchuk97Ilja commented on homework6/homework6_2.js
> +function newGenerateId() {
Создаем айдишник по кол-ву миллисекунд. Не бывает одинакового времени создания заявок.

2019-04-30 16:26 UTC, ruslanmalogulko requested changes

2019-04-30 16:26 UTC, ruslanmalogulko commented on homework6/homework6_2.js
> +    return parent.contains(child);
.contains будет проверять всю цепочку родителей. Тебе нужно проверить на непосредственное родительство

2019-04-30 16:26 UTC, ruslanmalogulko commented on homework6/homework6_2.js
> +let numElementsLi = getUlSelector.children;
Среди детей могут оказаться не только li элементы. Нужно посчитать именно li

2019-04-30 22:16 UTC, ruslanmalogulko commented on homework6/homework6_2.js
> +let numElementsLi = document.querySelectorAll('li')
может getUlSelector.querySelectorAll('li')? или document.querySelectorAll('ul > li') ?

2019-04-30 22:17 UTC, ruslanmalogulko commented on homework6/homework6_2.js
> +/*function isParent(parent,child) {
можно удалить этот блок если он больше не нужен

2019-05-01 08:53 UTC, ruslanmalogulko approved these changes

2019-05-01 08:53 UTC, merged